import re
from pathlib import Path

import frontmatter as frontmatter_lib

from .registry import ToolDefinition
from ..config import settings
from .github_tools import _create_branch, _commit_files, _create_pr


def _get_soul_content(context=None) -> str:
    if not context or not context.agent_slug:
        return "Error: agent context not available"
    soul_path = Path(settings.souls_dir) / f"{context.agent_slug}.soul.md"
    if not soul_path.exists():
        return f"Error: soul file not found for '{context.agent_slug}'"
    return soul_path.read_text(encoding="utf-8")


def _propose_soul_update(new_body: str, context=None) -> str:
    """Propose a soul update by opening a GitHub PR.

    Only the Markdown body may change. Frontmatter (capabilities, model,
    cost_guardrails) is immutable from the agent's perspective.
    """
    if not context or not context.agent_slug:
        return "Error: agent context not available"

    slug = context.agent_slug
    run_id = context.run_context.run_id[:8] if context.run_context else "unknown"
    soul_path = Path(settings.souls_dir) / f"{slug}.soul.md"

    if not soul_path.exists():
        return f"Error: soul file not found for '{slug}'"

    current_raw = soul_path.read_text(encoding="utf-8")
    current_post = frontmatter_lib.loads(current_raw)

    if new_body.strip() == current_post.content.strip():
        return "No changes detected in soul body — nothing to propose."

    # Rebuild the full .soul.md preserving the exact original frontmatter
    new_soul_md = frontmatter_lib.dumps(frontmatter_lib.Post(new_body.strip(), **current_post.metadata))

    # Defense-in-depth: verify frontmatter is unchanged after round-trip
    new_post = frontmatter_lib.loads(new_soul_md)
    if current_post.metadata != new_post.metadata:
        return "Error: frontmatter changes are not allowed. Only the Markdown body may be modified."

    branch_name = f"soul/{slug}/run-{run_id}"

    create_result = _create_branch(branch_name, "main")
    if "GitHub error" in create_result and "already exists" not in create_result.lower():
        return f"Failed to create branch: {create_result}"

    file_path = f"souls/{slug}.soul.md"
    commit_result = _commit_files(branch_name, {file_path: new_soul_md}, f"soul({slug}): update from run-{run_id}")
    if "Error" in commit_result or "GitHub error" in commit_result:
        return f"Failed to commit soul update: {commit_result}"

    pr_result = _create_pr(
        title=f"soul({slug}): self-improvement from run-{run_id}",
        body=(
            f"Proposed soul improvement for `{slug}` agent after run `{run_id}`.\n\n"
            f"**Changes:** Markdown body only — frontmatter is unchanged.\n\n"
            f"Auto-generated by the soul self-improvement loop."
        ),
        head_branch=branch_name,
        base_branch="main",
    )

    pr_url = _extract_pr_url(pr_result)
    return f"Soul PR created. {pr_result}\nOUTPUT soul_pr_url: {pr_url}"


def _extract_pr_url(pr_result: str) -> str:
    match = re.search(r"(https://github\.com/\S+)", pr_result)
    return match.group(1) if match else pr_result


GET_SOUL_CONTENT = ToolDefinition(
    name="get_soul_content",
    description="Read the full content of your own .soul.md file",
    input_schema={"type": "object", "properties": {}, "required": []},
    handler=_get_soul_content,
)

PROPOSE_SOUL_UPDATE = ToolDefinition(
    name="propose_soul_update",
    description=(
        "Propose an update to your soul by opening a GitHub PR with an improved Markdown body. "
        "Only the Markdown body (everything after the YAML frontmatter) may change. "
        "Capabilities, model, and cost_guardrails are read-only and will be rejected if modified."
    ),
    input_schema={
        "type": "object",
        "properties": {
            "new_body": {
                "type": "string",
                "description": "The full new Markdown body for the soul (everything after the YAML frontmatter).",
            },
        },
        "required": ["new_body"],
    },
    handler=_propose_soul_update,
)
